### ISSUE TITLE
test handle now failing

### ISSUE THREAD

**Issue by edhartnett** [gptl/GPTL-fortran#22]
Not sure when this broke, but it was working recently.

The test "handle" now fails like this:

```
ed@mikado:~/tmp/GPTL-fortran/test$ ./handle 
GPTL error:GPTL error:GPTLstop_handle: timer loop was already off.
GPTL error:GPTLstop: timer loop was already off.
GPTLstop: timer loop was already off.
GPTL error:GPTLstop: timer loop was already off.
GPTL warning:
Program received signal SIGSEGV: Segmentation fault - invalid memory reference.

Backtrace for this error:
#0  0x7f4012be82da in ???
#1  0x7f4012be7503 in ???
#2  0x7f40125ebf1f in ???
#3  0x7f401273b5a1 in ???
#4  0x7f4012607a44 in ???
#5  0x7f4012609cb9 in ???
#6  0x7f401260b67f in ???
#7  0x7f4012608725 in ???
#8  0x7f40126df767 in ???
#9  0x7f4012fb6ba4 in vfprintf
	at /usr/include/x86_64-linux-gnu/bits/stdio2.h:127
#10  0x7f4012fb6ba4 in GPTLwarn
	at /home/ed/Downloads/gptl-all-1.0.0/GPTL/src/util.c:67
#11  0x7f4012fb2ec5 in update_stats
	at /home/ed/Downloads/gptl-all-1.0.0/GPTL/src/gptl.c:1222
#12  0x7f4012fb2ec5 in GPTLstop_handle
	at /home/ed/Downloads/gptl-all-1.0.0/GPTL/src/gptl.c:1154
#13  0x7f4012faeded in gptlstop_handle_
	at /home/ed/Downloads/gptl-all-1.0.0/GPTL/src/f_wrappers.c:313
#14  0x55e54fdadc55 in MAIN__._omp_fn.0
	at /home/ed/tmp/GPTL-fortran/test/handle.F90:19
#15  0x7f40129b497d in ???
#16  0x7f40117936da in ???
#17  0x7f40126ce88e in ???
#18  0xffffffffffffffff in ???
Segmentation fault (core dumped)
```

I am going to turn this test off to get travis working, but no other changes should be merged until this is fixed.

**Comment by jmrosinski** [comment]
You should be using the "working" branch I mentioned earlier. This bug was
fixed there some days ago. I won't close this issue until I know it also
works for you.

**Comment by edhartnett** [comment]
OK, not sure what you mean by working branch.

Tests are against master. 

Can you PR whatever changes are needed to get this test working again on master?

**Comment by jmrosinski** [comment]
"working" is the name of the branch. There was already a "development" that
I need to determine the state of, so I needed a different name.

**Comment by edhartnett** [comment]
master is the canonical branch. Please put up PRs against master with changes. Each PR will automatically be run through travis testing.
